### ISSUE TITLE
机器人无法在线

### ISSUE THREAD

**Issue by xxw-iwnl** [shuyangzhang/Kyouka#28]
按照步骤在阿里云上部署成功了 但是kook里机器人还是离线状态 我猜想是不是端口的问题 请问相关端口有什么需要开放的嘛

**Comment by Hinanawimoko** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
